name: InfernalPouch
main: MPouch\Main
api: [3.0.0, 3.0.0-ALPHA11, 3.0.0-ALPHA12] 
version: 1.0
author: EmeraldAssasinYT
commands:
  infernalpouch:
    description: "§l§5I§8N§r§7: Custom Money Pouches"
